action_transformer: config/action_transformer/relative_25.yaml
gui: false
level: config/level/level_train4.yaml
model_name: models/ppo_l4_obs_act_rew_beta_act_rel25_num_timesteps_2000000_time_07-05-13-52/best_model/best_model
model_type: ppo
num_timesteps: 2000000
observation_parser: config/observation_parser/action.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
