action_transformer: config/action_transformer/slow.yaml
gui: false
level: config/level/train2.yaml
model_name: models/ppo_t2_obs_min_rew_default_act_rel_num_timesteps_4000000_time_06-12-22-15/best_model/best_model
num_timesteps: 4000000
observation_parser: config/observation_parser/minimal.yaml
rewarder: config/rewarder/gamma_june12_rewarder.yaml
seed: 0
