action_transformer: config/action_transformer/relative.yaml
gui: false
level: config/level/level_train4.yaml
model_name: models/ppo_l4_obs_actNorm_rew_beta_act_rel_num_timesteps_5000000_time_07-07-13-54/best_model/best_model
model_type: ppo
num_timesteps: 5000000
observation_parser: config/observation_parser/action_normalized.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
