action_transformer: config/action_transformer/medium.yaml
gui: false
level: config/level/level3.yaml
model_name: models/ppo_l3_obs_sca_rew_beta_act_rel_num_timesteps_4000000_time_06-16-22-20/best_model/best_model
num_timesteps: 4000000
observation_parser: config/observation_parser/scaramuzza.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
