action_transformer: config/action_transformer/double_relative.yaml
gui: false
level: config/level/level_train4.yaml
model_name: models/ppo_l4_obs_act2Norm_rew_beta_act_2rel_num_timesteps_5000000_time_07-08-16-13/best_model/best_model
model_type: ppo
num_timesteps: 5000000
observation_parser: config/observation_parser/action2_normalized.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
