action_transformer: config/action_transformer/faster.yaml
gui: false
level: config/level/train2.yaml
model_name: models/ppo_t2_obs_act_rew_default_act_rel_num_timesteps_4000000_time_06-13-07-29/best_model/best_model
num_timesteps: 4000000
observation_parser: config/observation_parser/action.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
