action_transformer: config/action_transformer/medium.yaml
gui: false
level: config/level/level_train2.yaml
model_name: models/ppo_l2_obs_rel_corners_rew_default_act_rel_num_timesteps_4000000_time_06-23-20-48/best_model/best_model
num_timesteps: 4000000
observation_parser: config/observation_parser/relative_corners.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
