collision:  -10.0
out_of_bounds: -10.0
times_up: -10.0
dist_to_gate_mul: 1.0
end_reached: 10.0
gate_reached: 10.0
z_penalty: 0.0
z_penalty_threshold: 2.0
action_smoothness: 0.0
body_rate_penalty: -0.01

shortname: "acmpc"
