action_transformer: config/action_transformer/faster.yaml
gui: false
level: config/level/train1.yaml
model_name: models/ppo_t1_obs_rel_rew_default_act_rel_num_timesteps_500000_time_06-10-16-18/best_model/best_model
num_timesteps: 500000
observation_parser: config/observation_parser/relative.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
