action_transformer: config/action_transformer/double_relative_100.yaml
gui: false
level: config/level/level_train4.yaml
model_name: models/ppo_l4_obs_act2Norm_rew_beta_act_2rel100_num_timesteps_10000000_time_07-09-18-13/best_model/best_model
model_type: ppo
num_timesteps: 10000000
observation_parser: config/observation_parser/action2_normalized.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
