action_transformer: config/action_transformer/medium.yaml
gui: false
level: config/level/train1.yaml
model_name: models/ppo_t1_obs_sca_rew_acmpc2_act_rel_num_timesteps_1000000_time_06-15-12-24/best_model/best_model
num_timesteps: 1000000
observation_parser: config/observation_parser/scaramuzza.yaml
rewarder: config/rewarder/acmpc_soft_rewarder.yaml
seed: 0
