action_transformer: config/action_transformer/no_yaw.yaml
gui: false
level: config/level/level_train2.yaml
model_name: models/ppo_l2_obs_act_rew_beta_act_noyaw_num_timesteps_5000000_time_07-03-21-40/best_model/best_model
model_type: ppo
num_timesteps: 5000000
observation_parser: config/observation_parser/action.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
