action_transformer: config/action_transformer/double_relative_25.yaml
gui: false
level: config/level/level_train3.yaml
model_name: models/ppo_l3_obs_actNorm_rew_beta_act_2rel25_num_timesteps_2000000_time_07-05-15-10/best_model/best_model
model_type: ppo
num_timesteps: 2000000
observation_parser: config/observation_parser/action_normalized.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
