action_transformer: config/action_transformer/medium.yaml
gui: true
level: config/level/level0.yaml
model_name: models/ppo_l0_obs_path_rew_beta_act_rel_num_timesteps_1000000_time_06-19-16-21/best_model/best_model
num_timesteps: 1000000
observation_parser: config/observation_parser/path.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
