action_transformer: config/action_transformer/double_relative100.yaml
gui: false
level: config/level/level_train0.yaml
model_name: models/ppo_l0_obs_act_rew_beta_act_2rel_num_timesteps_5000000_time_06-30-23-01/best_model/best_model
model_type: ppo
num_timesteps: 5000000
observation_parser: config/observation_parser/action.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
