action_transformer: config/action_transformer/medium.yaml
gui: false
level: config/level/train2.yaml
model_name: models/ppo_t2_obs_sca_rew_beta_act_rel_num_timesteps_2000000_time_06-15-16-44/best_model/best_model
num_timesteps: 2000000
observation_parser: config/observation_parser/scaramuzza.yaml
rewarder: config/rewarder/beta_june07_rewarder.yaml
seed: 0
